### ISSUE TITLE
server vs client event

### ISSUE THREAD

**Issue by maghuro** [Xentrk/x3mRouting#10]
on route all vpn server, I think it should be more efficient to have the roules on vpnclientX-route-up/down or vpnclientX-up/down.

Sometimes I lose internet connection and the VPN client goes down. When it goes UP, for some reason, despite of the iptables rules are still defined, I can't use the VPN server on internet, only WAN.
I tested and changes the vpnserver rules to vpnclient and, when losing connection, they are deleted and restored properly on VpnClient events.
Consider that, please.

**Comment by Xentrk** [comment]
I'll make the change in the new version since it's almost done.
