### ISSUE TITLE
"Checking if IPSET backup file exists" prevents unattended execution

### ISSUE THREAD

**Issue by h0me5k1n** [Xentrk/x3mRouting#42]
I'm looking to automatically update routing rules based on information discovered from other sources. This involves deleting and recreating an IPSET list to edit the entries but, when deleting an IPSET whilst a backup exists, the processing stops to wait for user input.

Is it possible to pass a parameter with "del" that tells x3mrouting to either keep or delete the backup without requirement manual intervention every time? I cannot see any logic in the script itself. It looks like it will always ask for input here.

**Comment by Xentrk** [comment]
I should be able to add that feature. I'll take a look at it.

**Comment by Xentrk** [comment]
I just pushed an update for the request. Specify "del=force" instead of "del" parameter to prevent prompts for file deletion.
