### ISSUE TITLE
Feature Request: Quick disable button in config GUI

### ISSUE THREAD

**Issue by Murgeye** [Xentrk/x3mRouting#5]
Hey,

thank you for these scripts (way easier to use than what I manually constructed in OpenWRT using mwan3 before)!

What I would love to see is a enable/disable checkbox in the OpenVPN GUI that allows me to disable routing quickly for a IPSET without deleting it from the list completely and having to re-add it later.

This would be nice for quickly changing countries for streaming services.

If you give me some pointers on where to start, I might have the time to try to implement it myself and send you a pull request this or next weekend.

**Comment by Xentrk** [comment]
In order for the rules to be applied or removed, a restart of the vpn client is required by pressing the Apply button.
