### ISSUE TITLE
does this work with Dual WAN enabled?

### ISSUE THREAD

**Issue by knoid** [Xentrk/x3mRouting#6]
Hi!

I found you via your `IPSET_Domains.sh` script and I've been using it without major issues. Recently I installed a 2nd ISP because they are not really stable and noticed some requests are not being routed properly. Does this repo work using Dual Wan?

Thanks and great work!

**Comment by Xentrk** [comment]
Sorry for the very late reply. I primarily monitor the support thread on snbforums for Q&A. There is one person who was able to get it working with dual WAN with some modifications. I will look into adding this feature in a future version. See the post on [snbforums ](https://www.snbforums.com/threads/x3mrouting-selective-routing-for-asuswrt-merlin-firmware.57793/page-4#post-512677)and follow the discussion on how he got it to work.
