### ISSUE TITLE
Route all vpn traffic

### ISSUE THREAD

**Issue by maghuro** [Xentrk/x3mRouting#7]
This script isn't working because it won't get triggered on vpn events.
I was looking to the code:
`Download_File /jffs/scripts/x3mRouting openvpn-event`
Shouldn't this file to to `/jffs/scripts/` instead?! So it can be triggered by vpn events?I think that's why isn't working, because it won't gets triggered at the file is on the wrong location

**Comment by Xentrk** [comment]
The install script has been patched to add the /jffs/scripts/openvpn-event file and the required entry if it does not exist.
